---
server:
  port: 9000

spring:
  application:
    name: s3-service

eureka:
  instance:
    hostname:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
